services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      MAIN_URL: "https://postiz.alphasync.ai"
      FRONTEND_URL: "https://postiz.alphasync.ai"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.alphasync.ai/api"
      JWT_SECRET: "kj34h5kjh23k4jh5k23jh4k5jh23k4jh5k2j3h4k5jh23k4jh5"
      DATABASE_URL: "postgresql://postiz-user:postiz-password@localhost:5432/postiz-db"
      REDIS_URL: "redis://localhost:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
      POSTGRES_PASSWORD: "postiz-password"
      POSTGRES_USER: "postiz-user"
      POSTGRES_DB: "postiz-db"
    volumes:
      - postiz-data:/config/
      - postiz-uploads:/uploads/
    ports:
      - 5000:5000

volumes:
  postiz-data:
    external: false
  postiz-uploads:
    external: false
